services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      -  /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity